title: Phaser Game 1 by XAssassin
email:
description: >- # this means to ignore newlines until "baseurl:"

#baseurl: "/WebsiteContent" # the subpath of your site, e.g. /blog
#url: "https://xassassin321.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
#markdown: kramdown
#theme options : minima, jekyll-theme-minimal, 
theme: minima

plugins:
  - jekyll-asciidoc
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-gist
  - jekyll-paginate
  - jekyll-archives


asciidoc:
  ext: asciidoc,adoc,ad

asciidoctor: {}
